### ISSUE TITLE
Game crashes on loading of mod

### ISSUE THREAD

**Issue by Jens12341234** [craftycram/GarageVehicleSavePlugin#1]
When I load the plugin, the game crashes. Is it compatible with LSPDFR 0.4.8?

**Comment by craftycram** [comment]
hey, as far as i know it should be compatible. i just wasn't able to update it yet cause my pc died, but i'll update it asap.
until then can you provide me with your RagePluginHook.log file so I can check what exactly caused the error?
you should be able to drag&drop the file into a comment here on github or else feel free to join my [discord](https://discord.gg/WfXSUSw) and paste it in the #gv-support channel

**Comment by Jens12341234** [comment]
It crashed one time and now it works fine, awsome mod btw

**Comment by craftycram** [comment]
alright awesome. thanks
I'm closing this issue for now. if you have any more issues feel free to open it again at any time.
